# This file is a template, and might need editing before it works on your project.
image: docker.io/golang:latest

variables:
  GITLAB_CI_YML_VERSION: "1.0"

stages:
  - test
  - build

before_script:
  - env
  - export GOPATH=$GOPATH$CI_BUILDS_DIR
  - export GO111MODULE=on
  - export GOPROXY=https://goproxy.io,direct
  - export GOSUMDB=off
  - ip a
  - go version
  - go env

go-fmt:
  stage: test
  script:
    - GOFMT_DIFF=$(gofmt -l . | grep -v vendor;true)
    - if [[ -n $GOFMT_DIFF ]];then echo -e "The go source files aren't gofmt formatted. please gofmt the following go source files!!!\n"${GOFMT_DIFF} && exit 1;fi
  tags:
    - att-docker-runner

# golangci-lint:
#   image: docker.io/golangci/golangci-lint
#   stage: test
#   script:
#     - golangci-lint run -v --timeout=10m
#   tags:
#     - att-docker-runner

# FIXME：并发问题导致用例不过，已反馈给go-zero，先屏蔽
unitest:
  stage: test
  script:
    #- go test -race $(go list ./... | grep -v /vendor/)
    - go test -race $(go list ./... | grep -v -E "collection|load|breaker") -v
  tags:
    - att-docker-runner
